### ISSUE TITLE
Open match in a new window (split)

### ISSUE THREAD

**Issue by veelenga** [ramele/agrep#2]
When i hit enter on a result in Agrep buffer, the file is opened in a previous (existed) window. Sometimes this is not desired as it may hide the stuff i'm working on at that moment. What would be nice is to have a hotkey (like C-v and C-h) to open the matched result in a split (vertical or horizontal).

Well, the desired effect is possible to achieve doing slip first and then running agrep command. So, your working file will be opened even if you choose a match from the result list. But that is not really convenient as you don't always know will you choose something or not.

I believe this is possible to do setting [options for Agrep window](https://github.com/ramele/agrep/blob/master/doc/agrep.txt#L130-L136). The naive way to do this is the following:

```vim
if !exists('s:agrep_cmd')
  nnoremap <C-v> :vs<cr>:Anext<cr>
  nnoremap <C-h> :sp<cr>:Anext<cr>
endif

```
![mar-09-2017 12-24-13](https://cloud.githubusercontent.com/assets/3624712/23746098/613b6d54-04c3-11e7-814c-a21a45ce553b.gif)

But that of course splits agrep window, and not the original (existed window) which is not really good. Could you please suggest the better way to do that?

**Comment by ramele** [comment]
I've added a new option for that (agrep_results_win_sp_mod). Let me know how it works for you.
BTW, I can see in your gif that your agrep window has no syntax highlighting, and the raw data is displayed instead and I'm wondering why. How did you install this plugin?

**Comment by veelenga** [comment]
Yup, that works for me. Thank you 👍 

Regarding syntax highlighting, in most cases highlighting is present, but sometimes there is a raw data. I don't know why that happens and it is not really an issue for me. I will let you know if i find preconditions for this.

I installed it via vim-plug. Here is my [vimrc](https://github.com/veelenga/dotfiles/blob/master/vimrc)...
