### ISSUE TITLE
nvim support

### ISSUE THREAD

**Issue by markwallsgrove** [ramele/agrep#3]
`agrep` doesn't seem to support nvim. Is there something I can do to resolve this issue? I am running `NVIM 0.2.0-dev`.

![image](https://cloud.githubusercontent.com/assets/6328824/23831874/85e9db30-0721-11e7-8fc0-dc708203f051.png)

**Comment by ramele** [comment]
I don't have much experience with nvim, but I believe that it can be done by replacing the async parts with nvim job control API. However, I don't think that nvim has an option to redirect the job output to a buffer like vim does, so the implementation might be much more complicated and slower.
