### ISSUE TITLE
issue when closing the grep window with :bd

### ISSUE THREAD

**Issue by justrajdeep** [ramele/agrep#4]
Hi

I love the plugin. Thanks for the great work!!!
I am seeing the following issue.
lets say i do a search, it opens the search result in a split as shown below

![image](https://cloud.githubusercontent.com/assets/3525867/24471342/d5c19c1c-148f-11e7-9f4a-c3447b6de585.png)

If i close the window using `:bd` and then i repeat the search it loses the formatting as shown below

![image](https://cloud.githubusercontent.com/assets/3525867/24471450/2667fd50-1490-11e7-9983-35fa8fa3f4c6.png)

This happens only if i close the search result using `:bd`, if i close it using `:q` the formatting is retained.

Please look into the issue
Thanks.

**Comment by ramele** [comment]
Hi,

I fixed the issue, please try the last commit.

**Comment by justrajdeep** [comment]
Thanks. the issue is resolved now.
